<?php

add_action( 'acf/include_fields', function() {
if ( ! function_exists( 'acf_add_local_field_group' ) ) {
return;
}

acf_add_local_field_group( array(
'key' => 'group_67d3ed472493e',
'title' => 'Navigation menu items',
'fields' => array(
array(
'key' => 'field_67d3ed475835b',
'label' => 'Icons',
'name' => 'icons',
'aria-label' => '',
'type' => 'select',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'choices' => array(
'home' => 'Maison',
'plane' => 'Avion',
'pot' => 'Casserole',
'user' => 'Personnage',
),
'default_value' => false,
'return_format' => 'value',
'multiple' => 0,
'allow_null' => 0,
'allow_in_bindings' => 0,
'ui' => 0,
'ajax' => 0,
'placeholder' => '',
),
),
'location' => array(
array(
array(
'param' => 'nav_menu',
'operator' => '==',
'value' => 'location/header',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
'key' => 'group_67d7f7203500a',
'title' => 'Site option',
'fields' => array(
array(
'key' => 'field_67d7f72073951',
'label' => 'Company name',
'name' => 'option_company_name',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_67d7f739ab873',
'label' => 'mail',
'name' => 'option_mail',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
),
array(
'key' => 'field_67d7f745ab874',
'label' => 'number',
'name' => 'option_number',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
),
),
'location' => array(
array(
array(
'param' => 'options_page',
'operator' => '==',
'value' => 'site-options',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
'key' => 'group_67c1c26f0dbf0',
'title' => 'Trip field',
'fields' => array(
array(
'key' => 'field_67c1c26fd45b0',
'label' => 'Appréciation du voyage',
'name' => 'rating',
'aria-label' => '',
'type' => 'select',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '50',
'class' => '',
'id' => '',
),
'choices' => array(
0 => '0 étoile',
1 => '1 étoile',
2 => '2 étoiles',
3 => '3 étoiles',
4 => '4 étoiles',
5 => '5 étoiles',
),
'default_value' => false,
'return_format' => 'value',
'multiple' => 0,
'allow_null' => 0,
'allow_in_bindings' => 0,
'ui' => 0,
'ajax' => 0,
'placeholder' => '',
),
array(
'key' => 'field_67c1c400d45b1',
'label' => 'Date de début du voyage',
'name' => 'Departure',
'aria-label' => '',
'type' => 'date_picker',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '25',
'class' => '',
'id' => '',
),
'display_format' => 'd/m/Y',
'return_format' => 'U',
'first_day' => 1,
'allow_in_bindings' => 0,
),
array(
'key' => 'field_67c1c4b0d45b2',
'label' => 'Date de fin du voyage',
'name' => 'return',
'aria-label' => '',
'type' => 'date_picker',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '25',
'class' => '',
'id' => '',
),
'display_format' => 'd/m/Y',
'return_format' => 'U',
'first_day' => 1,
'allow_in_bindings' => 0,
),
array(
'key' => 'field_67c1d514f75b4',
'label' => 'Points-clés',
'name' => 'Key-points',
'aria-label' => '',
'type' => 'wysiwyg',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'allow_in_bindings' => 0,
'tabs' => 'visual',
'toolbar' => 'basic',
'media_upload' => 0,
'delay' => 0,
),
array(
'key' => 'field_67c1d57df75b5',
'label' => 'Récits de voyages',
'name' => 'Story',
'aria-label' => '',
'type' => 'wysiwyg',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'allow_in_bindings' => 0,
'tabs' => 'all',
'toolbar' => 'full',
'media_upload' => 1,
'delay' => 0,
),
array(
'key' => 'field_67c1d75dc7585',
'label' => 'Image affichée sur le coté',
'name' => 'side_img',
'aria-label' => '',
'type' => 'image',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'id',
'library' => 'all',
'min_width' => 420,
'min_height' => 420,
'min_size' => '',
'max_width' => '',
'max_height' => '',
'max_size' => '',
'mime_types' => '',
'allow_in_bindings' => 0,
'preview_size' => 'medium',
),
),
'location' => array(
array(
array(
'param' => 'post_type',
'operator' => '==',
'value' => 'travel',
),
),
),
'menu_order' => 0,
'position' => 'acf_after_title',
'style' => 'seamless',
'label_placement' => 'top',
'instruction_placement' => 'field',
'hide_on_screen' => array(
0 => 'the_content',
),
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );
} );

